### PR TITLE
0.6.0

### PR DESCRIPTION
**Pull request by cbenhagen**
Some minor updates to keep the package up to date for Flutter 3.0.0.

### CODE REVIEW

**Comment by hcbpassos** [comment]
great work! thanks a lot ❤️

**Comment by hcbpassos** [comment]
closes #28

**Comment by cbenhagen** [comment]
You're welcome! Would you mind releasing the new version?

**Comment by hcbpassos** [comment]
sorry, i've been a bit distant from flutter, so i didn't even remember i had to do that lol 

thanks for the touch. 

i'll try to move the ownership to [flutter community](https://github.com/fluttercommunity/community), so the users can get a better experience when using this package :)

**Pull request merged**
